# Copyright 2018 The Crashpad Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//:copts.bzl", "CRASHPAD_COMMON_COPTS")

licenses(["notice"])

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = [
        "//:__subpackages__",
        "//:clients",
    ],
)

cc_library(
    name = "common_interface",
    srcs = [
        "crash_report_upload_thread.cc",
        "minidump_to_upload_parameters.cc",
    ],
    hdrs = [
        "crash_report_upload_thread.h",
        "mac/file_limit_annotation.h",
        "minidump_to_upload_parameters.h",
    ],
    copts = CRASHPAD_COMMON_COPTS,
    include_prefix = "handler",
    deps = [
        "//client:common",
        "//compat",
        "//snapshot",
        "//third_party/mini_chromium:base",
        "//util",
        "//util:net",
    ],
)

cc_library(
    name = "common_mac",
    srcs = ["mac/file_limit_annotation.cc"],
    applicable_licenses = ["//third_party/xnu:license"],
    copts = CRASHPAD_COMMON_COPTS,
    target_compatible_with = ["@platforms//os:macos"],
    deps = [
        ":common_interface",
        "//third_party/mini_chromium:base",
    ],
)

cc_library(
    name = "common",
    deps = [":common_interface"] + select({
        "@platforms//os:macos": [":common_mac"],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "handler_interface",
    srcs = [
        "handler_main.cc",
        "prune_crash_reports_thread.cc",
        "user_stream_data_source.cc",
    ],
    hdrs = [
        "handler_main.h",
        "linux/capture_snapshot.h",
        "linux/crash_report_exception_handler.h",
        "linux/cros_crash_report_exception_handler.h",
        "linux/exception_handler_server.h",
        "mac/crash_report_exception_handler.h",
        "mac/exception_handler_server.h",
        "prune_crash_reports_thread.h",
        "user_stream_data_source.h",
        "win/crash_report_exception_handler.h",
    ],
    copts = CRASHPAD_COMMON_COPTS,
    include_prefix = "handler",
    deps = [
        ":common",
        "//client",
        "//compat",
        "//minidump",
        "//snapshot",
        "//third_party/mini_chromium:base",
        "//tools:tool_support",
        "//util",
    ],
)

cc_library(
    name = "handler_mac",
    srcs = [
        "mac/crash_report_exception_handler.cc",
        "mac/exception_handler_server.cc",
    ],
    applicable_licenses = ["//third_party/xnu:license"],
    copts = CRASHPAD_COMMON_COPTS,
    include_prefix = "handler",
    target_compatible_with = ["@platforms//os:osx"],
    deps = [
        ":handler_interface",
        "//third_party/mini_chromium:base",
    ],
)

cc_library(
    name = "handler_linux",
    srcs = [
        "linux/capture_snapshot.cc",
        "linux/crash_report_exception_handler.cc",
        "linux/cros_crash_report_exception_handler.cc",
        "linux/exception_handler_server.cc",
    ],
    copts = CRASHPAD_COMMON_COPTS,
    include_prefix = "handler",
    target_compatible_with = ["@platforms//os:linux"],
    deps = [
        ":handler_interface",
        "//third_party/mini_chromium:base",
    ],
)

cc_library(
    name = "handler_win",
    srcs = [
        "win/crash_report_exception_handler.cc",
    ],
    copts = CRASHPAD_COMMON_COPTS + ["/wd4201"],
    include_prefix = "handler",
    target_compatible_with = ["@platforms//os:windows"],
    deps = [
        ":handler_interface",
        "//third_party/getopt",
        "//third_party/mini_chromium:base",
    ],
)

cc_library(
    name = "handler",
    visibility = ["//visibility:public"],
    deps = select({
        "@platforms//os:osx": [":handler_mac"],
        "@platforms//os:linux": [":handler_linux"],
        "@platforms//os:windows": [":handler_win"],
        "//conditions:default": [":handler_interface"],
    }),
)

cc_binary(
    name = "crashpad_handler",
    srcs = ["main.cc"],
    linkopts =
        select({
            "@platforms//os:windows": [
                # This prevents opening a console window when crashpad_handler.exe runs.
                "/SUBSYSTEM:WINDOWS",
            ],
            "@platforms//os:macos": [
                "-l bsm",
            ],
            "//conditions:default": [],
        }),
    visibility = ["//visibility:public"],
    deps = [
        ":handler",
        "//compat",
        "//third_party/mini_chromium:base",
        "//tools:tool_support",
    ] + select({
        "@platforms//os:linux": [
            "//client:pthread_create",
        ],
        "//conditions:default": [],
    }),
)

cc_binary(
    name = "crashpad_handler_console_exe",
    srcs = ["main.cc"],
    linkopts = ["/SUBSYSTEM:CONSOLE"],
    target_compatible_with = [
        "@platforms//os:windows",
    ],
    deps = [
        ":handler",
        "//compat",
        "//third_party/mini_chromium:base",
        "//tools:tool_support",
    ],
)

copy_file(
    name = "crashpad_handler_console",
    src = ":crashpad_handler_console_exe",
    out = "crashpad_handler.com",
)

cc_test(
    name = "crashpad_handler_test",
    srcs = ["minidump_to_upload_parameters_test.cc"] + select({
        "@platforms//os:linux": ["linux/exception_handler_server_test.cc"],
        "//conditions:default": [],
    }),
    copts = CRASHPAD_COMMON_COPTS + select({
        "@platforms//os:linux": ["-Wno-multichar"],
        "//conditions:default": [],
    }),
    deps = [
        ":common",
        ":handler",
        "//:internal",
        "//client",
        "//compat",
        "//minidump:test_support",
        "//snapshot",
        "//snapshot:test_support",
        "//test",
        "//test:googlemock_main",
        "//third_party/mini_chromium:base",
        "//util",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "crashpad_handler_test_extended_handler",
    testonly = True,
    srcs = [
        "crashpad_handler_test_extended_handler.cc",
    ],
    copts = CRASHPAD_COMMON_COPTS,
    deps = [
        "//:internal",
        "//compat",
        "//minidump:test_support",
        "//third_party/mini_chromium:base",
        "//tools:tool_support",
    ],
)

cc_binary(
    name = "fake_handler_that_crashes_at_startup",
    testonly = True,
    srcs = ["win/fake_handler_that_crashes_at_startup.cc"],
    target_compatible_with = [
        "@platforms//os:windows",
    ],
)
